version: "3.8"
services:
  mc-server-info:
    build: .
    ports:
      - "1701:1701"
    environment:
      - SERVER_vanilla=192.168.1.123:25565
      - DISCORD_TOKEN=INSERT_TOKEN_HERE
      - CHANNEL_ID=INSERT_ID_HERE
    restart: unless-stopped