version: "3.8"
services:
  mc-server-info:
    image: sah17/mc-server-info:latest
    container_name: mc-server-info
    ports:
      - "1701:1701"
    volumes:
      - /DATA/AppData/mc-server-info/data:/data
    environment:
      - SERVER_vanillabusters=example.com:25565
      - SERVER_roguebusters=example.org:25565
      - DISCORD_TOKEN=your_token
      - CHANNEL_ID=your_channel_id
    restart: unless-stopped